name: Keep Streak Green

on:
  schedule:
    
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  keep-green:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      
      - name: Make a daily commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          echo "Last heartbeat: $(date)" > heartbeat.txt
          git add heartbeat.txt
          git commit -m "chore: daily heartbeat"
          git push
